// Classes that should be considered stable by the Compose compiler
// https://developer.android.com/develop/ui/compose/performance/stability/fix#configuration-file

// Java Time classes
java.time.LocalDate
java.time.LocalDateTime
java.time.ZonedDateTime
java.time.Instant

// Kotlinx Immutable Collections
kotlinx.collections.immutable.*

// TextFieldState is internally mutable but Compose tracks it
androidx.compose.foundation.text.input.TextFieldState